"""initial

Revision ID: 5231deccd9ce
Revises: 
Create Date: 2026-06-21 17:45:27.475643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5231deccd9ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('conversations', sa.Column('is_processing', sa.Boolean(), nullable=True))
    op.execute("UPDATE conversations SET is_processing = FALSE WHERE is_processing IS NULL")
    op.alter_column('conversations', 'is_processing',
                    existing_type=sa.Boolean(),
                    nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_processing')
    # ### end Alembic commands ###
