services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - D:/docker-volumes/ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart:  "no"
#    networks:
#      - ollama_network   # ← за ollama

  postgres:
    image: postgres:16-alpine
    container_name: postgres_users_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - D:/docker-volumes/postgres:/var/lib/postgresql/data
    restart:  "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  chromadb:
      image: chromadb/chroma:latest
      container_name: chromadb
      ports:
        - "8001:8000"
      volumes:
        - D:/docker-volumes/chromadb:/chroma/chroma
      restart:  "no"

#networks:
#  ollama_network:
#    external: true
#    name: ollama_network