services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - D:/docker-volumes/ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
#      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    networks:
      - ollama_network

networks:
  ollama_network:
    name: ollama_network
    driver: bridge